FISH-490 Remove JAXB API usage from the Payara Eclipse tools
payara/ecosystem-eclipse-plugin pull request #31
Opened 2020-10-20 09:35 UTC by jGauravGupta

2020-10-20 13:48 UTC, dmatej requested changes
I didn't try it yet, but except my comments it seems alright

2020-10-20 13:48 UTC, dmatej commented on plugins/org.eclipse.payara.tools/src/org/eclipse/payara/tools/internal/SystemLibrariesSetting.java
> +                settings = handler.getSystemLibrariesSetting();//(SystemLibrariesSetting) JAXBContext.newInstance(SystemLibrariesSetting.class).createUnmarshaller().unmarshal(stream);
I see a comment to delete :-)

2020-10-20 13:48 UTC, dmatej commented on plugins/org.eclipse.payara.tools/src/org/eclipse/payara/tools/internal/SystemLibrariesSetting.java
> +            writer.close();
Resource leak on exception - you should close the writer in finally or use trywith (you can simply create a private method XMLStreamWriter createWriter();

2020-10-22 06:27 UTC, dmatej approved these changes

2020-10-22 06:32 UTC, merged

2020-10-22 06:32 UTC, jGauravGupta commented
Thanks @dmatej